### ISSUE TITLE
``_pytest._io`` ImportError

### ISSUE THREAD

**Issue by jameshcorbett** [ExaWorks/psi-j-python#102]
I ran into an exception while running the tests:

```
(37B) [corbett8@lassen709:psi-j-python]$ make tests -- --upload-results
PYTHONPATH=/usr/WS2/corbett8/ExaWorks/psi-j-python/src: python -m pytest -v --upload-results
ImportError while loading conftest '/usr/WS2/corbett8/ExaWorks/psi-j-python/tests/conftest.py'.
tests/conftest.py:20: in <module>
    from _pytest._io import TerminalWriter
E   ImportError: cannot import name 'TerminalWriter' from '_pytest._io' (/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/_pytest/_io/__init__.py)
make: *** [Makefile:14: tests] Error 4
```

The problem went away when I upgraded ``pytest`` from 4.3 to 6.2. So the easiest solution would be to require ``pytest >= X`` or similar in our requirements file. But I was wondering if there are other options available to us that wouldn't require ``_pytest`` imports. We could replace the line with ``from py.io import TerminalWriter`` but ``py`` is in maintenance mode. Any thoughts?

**Comment by hategan** [comment]
Maybe. That class fakes a terminal so that the output from tests can be displayed in all their colorful glory.

We should try to find an alternative, but don't mind requiring an updated pytest in the mean time.

**Comment by benclifford** [comment]
came here to open this same issue (I'm encountering it a bunch because I'm sharing environments with parsl which has version bounds for an old version of pytest)

putting a version constraint in psi-j-python is an ok solution for me - parsl will eventually update
